### ISSUE TITLE
自己紹介を作る - 白川

### ISSUE THREAD

**Issue by mi-bear** [chiroruxx/team_project#1]
白川です。
Issue を書いてみました。

- 2021−10 入学
- 情報アーキテクチャコース 1年生
- 普段は Fintech 企業の Engineering Manager をしています。
- Go がすき。

**Comment by chiroruxx** [comment]
よろしくおねがいします！

**Comment by polyu-17002407g** [comment]
こんにちは、よろしくお願いします。

**Comment by ebisennet** [comment]
よろしくおねがいしますぅ。

**Comment by AkihiroTokai** [comment]
よろしくお願いします!
